// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/group"
	"github.com/cloudreve/Cloudreve/v4/ent/membership"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// MembershipCreate is the builder for creating a Membership entity.
type MembershipCreate struct {
	config
	mutation *MembershipMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (mc *MembershipCreate) SetUserID(i int) *MembershipCreate {
	mc.mutation.SetUserID(i)
	return mc
}

// SetGroupID sets the "group_id" field.
func (mc *MembershipCreate) SetGroupID(i int) *MembershipCreate {
	mc.mutation.SetGroupID(i)
	return mc
}

// SetIsPrimary sets the "is_primary" field.
func (mc *MembershipCreate) SetIsPrimary(b bool) *MembershipCreate {
	mc.mutation.SetIsPrimary(b)
	return mc
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (mc *MembershipCreate) SetNillableIsPrimary(b *bool) *MembershipCreate {
	if b != nil {
		mc.SetIsPrimary(*b)
	}
	return mc
}

// SetCreatedAt sets the "created_at" field.
func (mc *MembershipCreate) SetCreatedAt(t time.Time) *MembershipCreate {
	mc.mutation.SetCreatedAt(t)
	return mc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mc *MembershipCreate) SetNillableCreatedAt(t *time.Time) *MembershipCreate {
	if t != nil {
		mc.SetCreatedAt(*t)
	}
	return mc
}

// SetExpiresAt sets the "expires_at" field.
func (mc *MembershipCreate) SetExpiresAt(t time.Time) *MembershipCreate {
	mc.mutation.SetExpiresAt(t)
	return mc
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (mc *MembershipCreate) SetNillableExpiresAt(t *time.Time) *MembershipCreate {
	if t != nil {
		mc.SetExpiresAt(*t)
	}
	return mc
}

// SetUser sets the "user" edge to the User entity.
func (mc *MembershipCreate) SetUser(u *User) *MembershipCreate {
	return mc.SetUserID(u.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (mc *MembershipCreate) SetGroup(g *Group) *MembershipCreate {
	return mc.SetGroupID(g.ID)
}

// Mutation returns the MembershipMutation object of the builder.
func (mc *MembershipCreate) Mutation() *MembershipMutation {
	return mc.mutation
}

// Save creates the Membership in the database.
func (mc *MembershipCreate) Save(ctx context.Context) (*Membership, error) {
	mc.defaults()
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MembershipCreate) SaveX(ctx context.Context) *Membership {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MembershipCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MembershipCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MembershipCreate) defaults() {
	if _, ok := mc.mutation.IsPrimary(); !ok {
		v := membership.DefaultIsPrimary
		mc.mutation.SetIsPrimary(v)
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		v := membership.DefaultCreatedAt()
		mc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MembershipCreate) check() error {
	if _, ok := mc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Membership.user_id"`)}
	}
	if _, ok := mc.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "Membership.group_id"`)}
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Membership.created_at"`)}
	}
	if _, ok := mc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Membership.user"`)}
	}
	if _, ok := mc.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "Membership.group"`)}
	}
	return nil
}

func (mc *MembershipCreate) sqlSave(ctx context.Context) (*Membership, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (mc *MembershipCreate) createSpec() (*Membership, *sqlgraph.CreateSpec) {
	var (
		_node = &Membership{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(membership.Table, nil)
	)

	_spec.OnConflict = mc.conflict
	if value, ok := mc.mutation.IsPrimary(); ok {
		_spec.SetField(membership.FieldIsPrimary, field.TypeBool, value)
		_node.IsPrimary = value
	}
	if value, ok := mc.mutation.CreatedAt(); ok {
		_spec.SetField(membership.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := mc.mutation.ExpiresAt(); ok {
		_spec.SetField(membership.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if nodes := mc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.UserTable,
			Columns: []string{membership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mc.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.GroupTable,
			Columns: []string{membership.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Membership.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MembershipUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (mc *MembershipCreate) OnConflict(opts ...sql.ConflictOption) *MembershipUpsertOne {
	mc.conflict = opts
	return &MembershipUpsertOne{
		create: mc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Membership.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mc *MembershipCreate) OnConflictColumns(columns ...string) *MembershipUpsertOne {
	mc.conflict = append(mc.conflict, sql.ConflictColumns(columns...))
	return &MembershipUpsertOne{
		create: mc,
	}
}

type (
	// MembershipUpsertOne is the builder for "upsert"-ing
	//  one Membership node.
	MembershipUpsertOne struct {
		create *MembershipCreate
	}

	// MembershipUpsert is the "OnConflict" setter.
	MembershipUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *MembershipUpsert) SetUserID(v int) *MembershipUpsert {
	u.Set(membership.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MembershipUpsert) UpdateUserID() *MembershipUpsert {
	u.SetExcluded(membership.FieldUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *MembershipUpsert) SetGroupID(v int) *MembershipUpsert {
	u.Set(membership.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *MembershipUpsert) UpdateGroupID() *MembershipUpsert {
	u.SetExcluded(membership.FieldGroupID)
	return u
}

// SetIsPrimary sets the "is_primary" field.
func (u *MembershipUpsert) SetIsPrimary(v bool) *MembershipUpsert {
	u.Set(membership.FieldIsPrimary, v)
	return u
}

// UpdateIsPrimary sets the "is_primary" field to the value that was provided on create.
func (u *MembershipUpsert) UpdateIsPrimary() *MembershipUpsert {
	u.SetExcluded(membership.FieldIsPrimary)
	return u
}

// ClearIsPrimary clears the value of the "is_primary" field.
func (u *MembershipUpsert) ClearIsPrimary() *MembershipUpsert {
	u.SetNull(membership.FieldIsPrimary)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *MembershipUpsert) SetCreatedAt(v time.Time) *MembershipUpsert {
	u.Set(membership.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MembershipUpsert) UpdateCreatedAt() *MembershipUpsert {
	u.SetExcluded(membership.FieldCreatedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *MembershipUpsert) SetExpiresAt(v time.Time) *MembershipUpsert {
	u.Set(membership.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *MembershipUpsert) UpdateExpiresAt() *MembershipUpsert {
	u.SetExcluded(membership.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *MembershipUpsert) ClearExpiresAt() *MembershipUpsert {
	u.SetNull(membership.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Membership.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MembershipUpsertOne) UpdateNewValues() *MembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Membership.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MembershipUpsertOne) Ignore() *MembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MembershipUpsertOne) DoNothing() *MembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MembershipCreate.OnConflict
// documentation for more info.
func (u *MembershipUpsertOne) Update(set func(*MembershipUpsert)) *MembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MembershipUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *MembershipUpsertOne) SetUserID(v int) *MembershipUpsertOne {
	return u.Update(func(s *MembershipUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MembershipUpsertOne) UpdateUserID() *MembershipUpsertOne {
	return u.Update(func(s *MembershipUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *MembershipUpsertOne) SetGroupID(v int) *MembershipUpsertOne {
	return u.Update(func(s *MembershipUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *MembershipUpsertOne) UpdateGroupID() *MembershipUpsertOne {
	return u.Update(func(s *MembershipUpsert) {
		s.UpdateGroupID()
	})
}

// SetIsPrimary sets the "is_primary" field.
func (u *MembershipUpsertOne) SetIsPrimary(v bool) *MembershipUpsertOne {
	return u.Update(func(s *MembershipUpsert) {
		s.SetIsPrimary(v)
	})
}

// UpdateIsPrimary sets the "is_primary" field to the value that was provided on create.
func (u *MembershipUpsertOne) UpdateIsPrimary() *MembershipUpsertOne {
	return u.Update(func(s *MembershipUpsert) {
		s.UpdateIsPrimary()
	})
}

// ClearIsPrimary clears the value of the "is_primary" field.
func (u *MembershipUpsertOne) ClearIsPrimary() *MembershipUpsertOne {
	return u.Update(func(s *MembershipUpsert) {
		s.ClearIsPrimary()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *MembershipUpsertOne) SetCreatedAt(v time.Time) *MembershipUpsertOne {
	return u.Update(func(s *MembershipUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MembershipUpsertOne) UpdateCreatedAt() *MembershipUpsertOne {
	return u.Update(func(s *MembershipUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *MembershipUpsertOne) SetExpiresAt(v time.Time) *MembershipUpsertOne {
	return u.Update(func(s *MembershipUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *MembershipUpsertOne) UpdateExpiresAt() *MembershipUpsertOne {
	return u.Update(func(s *MembershipUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *MembershipUpsertOne) ClearExpiresAt() *MembershipUpsertOne {
	return u.Update(func(s *MembershipUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *MembershipUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MembershipCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MembershipUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// MembershipCreateBulk is the builder for creating many Membership entities in bulk.
type MembershipCreateBulk struct {
	config
	err      error
	builders []*MembershipCreate
	conflict []sql.ConflictOption
}

// Save creates the Membership entities in the database.
func (mcb *MembershipCreateBulk) Save(ctx context.Context) ([]*Membership, error) {
	if mcb.err != nil {
		return nil, mcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Membership, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MembershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MembershipCreateBulk) SaveX(ctx context.Context) []*Membership {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MembershipCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MembershipCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Membership.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MembershipUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (mcb *MembershipCreateBulk) OnConflict(opts ...sql.ConflictOption) *MembershipUpsertBulk {
	mcb.conflict = opts
	return &MembershipUpsertBulk{
		create: mcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Membership.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mcb *MembershipCreateBulk) OnConflictColumns(columns ...string) *MembershipUpsertBulk {
	mcb.conflict = append(mcb.conflict, sql.ConflictColumns(columns...))
	return &MembershipUpsertBulk{
		create: mcb,
	}
}

// MembershipUpsertBulk is the builder for "upsert"-ing
// a bulk of Membership nodes.
type MembershipUpsertBulk struct {
	create *MembershipCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Membership.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MembershipUpsertBulk) UpdateNewValues() *MembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Membership.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MembershipUpsertBulk) Ignore() *MembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MembershipUpsertBulk) DoNothing() *MembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MembershipCreateBulk.OnConflict
// documentation for more info.
func (u *MembershipUpsertBulk) Update(set func(*MembershipUpsert)) *MembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MembershipUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *MembershipUpsertBulk) SetUserID(v int) *MembershipUpsertBulk {
	return u.Update(func(s *MembershipUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *MembershipUpsertBulk) UpdateUserID() *MembershipUpsertBulk {
	return u.Update(func(s *MembershipUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *MembershipUpsertBulk) SetGroupID(v int) *MembershipUpsertBulk {
	return u.Update(func(s *MembershipUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *MembershipUpsertBulk) UpdateGroupID() *MembershipUpsertBulk {
	return u.Update(func(s *MembershipUpsert) {
		s.UpdateGroupID()
	})
}

// SetIsPrimary sets the "is_primary" field.
func (u *MembershipUpsertBulk) SetIsPrimary(v bool) *MembershipUpsertBulk {
	return u.Update(func(s *MembershipUpsert) {
		s.SetIsPrimary(v)
	})
}

// UpdateIsPrimary sets the "is_primary" field to the value that was provided on create.
func (u *MembershipUpsertBulk) UpdateIsPrimary() *MembershipUpsertBulk {
	return u.Update(func(s *MembershipUpsert) {
		s.UpdateIsPrimary()
	})
}

// ClearIsPrimary clears the value of the "is_primary" field.
func (u *MembershipUpsertBulk) ClearIsPrimary() *MembershipUpsertBulk {
	return u.Update(func(s *MembershipUpsert) {
		s.ClearIsPrimary()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *MembershipUpsertBulk) SetCreatedAt(v time.Time) *MembershipUpsertBulk {
	return u.Update(func(s *MembershipUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *MembershipUpsertBulk) UpdateCreatedAt() *MembershipUpsertBulk {
	return u.Update(func(s *MembershipUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *MembershipUpsertBulk) SetExpiresAt(v time.Time) *MembershipUpsertBulk {
	return u.Update(func(s *MembershipUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *MembershipUpsertBulk) UpdateExpiresAt() *MembershipUpsertBulk {
	return u.Update(func(s *MembershipUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *MembershipUpsertBulk) ClearExpiresAt() *MembershipUpsertBulk {
	return u.Update(func(s *MembershipUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *MembershipUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MembershipCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MembershipCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MembershipUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
