// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/group"
	"github.com/cloudreve/Cloudreve/v4/ent/membership"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// MembershipUpdate is the builder for updating Membership entities.
type MembershipUpdate struct {
	config
	hooks    []Hook
	mutation *MembershipMutation
}

// Where appends a list predicates to the MembershipUpdate builder.
func (mu *MembershipUpdate) Where(ps ...predicate.Membership) *MembershipUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetUserID sets the "user_id" field.
func (mu *MembershipUpdate) SetUserID(i int) *MembershipUpdate {
	mu.mutation.SetUserID(i)
	return mu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (mu *MembershipUpdate) SetNillableUserID(i *int) *MembershipUpdate {
	if i != nil {
		mu.SetUserID(*i)
	}
	return mu
}

// SetGroupID sets the "group_id" field.
func (mu *MembershipUpdate) SetGroupID(i int) *MembershipUpdate {
	mu.mutation.SetGroupID(i)
	return mu
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (mu *MembershipUpdate) SetNillableGroupID(i *int) *MembershipUpdate {
	if i != nil {
		mu.SetGroupID(*i)
	}
	return mu
}

// SetIsPrimary sets the "is_primary" field.
func (mu *MembershipUpdate) SetIsPrimary(b bool) *MembershipUpdate {
	mu.mutation.SetIsPrimary(b)
	return mu
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (mu *MembershipUpdate) SetNillableIsPrimary(b *bool) *MembershipUpdate {
	if b != nil {
		mu.SetIsPrimary(*b)
	}
	return mu
}

// ClearIsPrimary clears the value of the "is_primary" field.
func (mu *MembershipUpdate) ClearIsPrimary() *MembershipUpdate {
	mu.mutation.ClearIsPrimary()
	return mu
}

// SetCreatedAt sets the "created_at" field.
func (mu *MembershipUpdate) SetCreatedAt(t time.Time) *MembershipUpdate {
	mu.mutation.SetCreatedAt(t)
	return mu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mu *MembershipUpdate) SetNillableCreatedAt(t *time.Time) *MembershipUpdate {
	if t != nil {
		mu.SetCreatedAt(*t)
	}
	return mu
}

// SetExpiresAt sets the "expires_at" field.
func (mu *MembershipUpdate) SetExpiresAt(t time.Time) *MembershipUpdate {
	mu.mutation.SetExpiresAt(t)
	return mu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (mu *MembershipUpdate) SetNillableExpiresAt(t *time.Time) *MembershipUpdate {
	if t != nil {
		mu.SetExpiresAt(*t)
	}
	return mu
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (mu *MembershipUpdate) ClearExpiresAt() *MembershipUpdate {
	mu.mutation.ClearExpiresAt()
	return mu
}

// SetUser sets the "user" edge to the User entity.
func (mu *MembershipUpdate) SetUser(u *User) *MembershipUpdate {
	return mu.SetUserID(u.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (mu *MembershipUpdate) SetGroup(g *Group) *MembershipUpdate {
	return mu.SetGroupID(g.ID)
}

// Mutation returns the MembershipMutation object of the builder.
func (mu *MembershipUpdate) Mutation() *MembershipMutation {
	return mu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (mu *MembershipUpdate) ClearUser() *MembershipUpdate {
	mu.mutation.ClearUser()
	return mu
}

// ClearGroup clears the "group" edge to the Group entity.
func (mu *MembershipUpdate) ClearGroup() *MembershipUpdate {
	mu.mutation.ClearGroup()
	return mu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MembershipUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MembershipUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MembershipUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MembershipUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MembershipUpdate) check() error {
	if _, ok := mu.mutation.UserID(); mu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Membership.user"`)
	}
	if _, ok := mu.mutation.GroupID(); mu.mutation.GroupCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Membership.group"`)
	}
	return nil
}

func (mu *MembershipUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(membership.Table, membership.Columns, sqlgraph.NewFieldSpec(membership.FieldGroupID, field.TypeInt), sqlgraph.NewFieldSpec(membership.FieldUserID, field.TypeInt))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.IsPrimary(); ok {
		_spec.SetField(membership.FieldIsPrimary, field.TypeBool, value)
	}
	if mu.mutation.IsPrimaryCleared() {
		_spec.ClearField(membership.FieldIsPrimary, field.TypeBool)
	}
	if value, ok := mu.mutation.CreatedAt(); ok {
		_spec.SetField(membership.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := mu.mutation.ExpiresAt(); ok {
		_spec.SetField(membership.FieldExpiresAt, field.TypeTime, value)
	}
	if mu.mutation.ExpiresAtCleared() {
		_spec.ClearField(membership.FieldExpiresAt, field.TypeTime)
	}
	if mu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.UserTable,
			Columns: []string{membership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.UserTable,
			Columns: []string{membership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.GroupTable,
			Columns: []string{membership.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.GroupTable,
			Columns: []string{membership.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{membership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MembershipUpdateOne is the builder for updating a single Membership entity.
type MembershipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MembershipMutation
}

// SetUserID sets the "user_id" field.
func (muo *MembershipUpdateOne) SetUserID(i int) *MembershipUpdateOne {
	muo.mutation.SetUserID(i)
	return muo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (muo *MembershipUpdateOne) SetNillableUserID(i *int) *MembershipUpdateOne {
	if i != nil {
		muo.SetUserID(*i)
	}
	return muo
}

// SetGroupID sets the "group_id" field.
func (muo *MembershipUpdateOne) SetGroupID(i int) *MembershipUpdateOne {
	muo.mutation.SetGroupID(i)
	return muo
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (muo *MembershipUpdateOne) SetNillableGroupID(i *int) *MembershipUpdateOne {
	if i != nil {
		muo.SetGroupID(*i)
	}
	return muo
}

// SetIsPrimary sets the "is_primary" field.
func (muo *MembershipUpdateOne) SetIsPrimary(b bool) *MembershipUpdateOne {
	muo.mutation.SetIsPrimary(b)
	return muo
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (muo *MembershipUpdateOne) SetNillableIsPrimary(b *bool) *MembershipUpdateOne {
	if b != nil {
		muo.SetIsPrimary(*b)
	}
	return muo
}

// ClearIsPrimary clears the value of the "is_primary" field.
func (muo *MembershipUpdateOne) ClearIsPrimary() *MembershipUpdateOne {
	muo.mutation.ClearIsPrimary()
	return muo
}

// SetCreatedAt sets the "created_at" field.
func (muo *MembershipUpdateOne) SetCreatedAt(t time.Time) *MembershipUpdateOne {
	muo.mutation.SetCreatedAt(t)
	return muo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (muo *MembershipUpdateOne) SetNillableCreatedAt(t *time.Time) *MembershipUpdateOne {
	if t != nil {
		muo.SetCreatedAt(*t)
	}
	return muo
}

// SetExpiresAt sets the "expires_at" field.
func (muo *MembershipUpdateOne) SetExpiresAt(t time.Time) *MembershipUpdateOne {
	muo.mutation.SetExpiresAt(t)
	return muo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (muo *MembershipUpdateOne) SetNillableExpiresAt(t *time.Time) *MembershipUpdateOne {
	if t != nil {
		muo.SetExpiresAt(*t)
	}
	return muo
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (muo *MembershipUpdateOne) ClearExpiresAt() *MembershipUpdateOne {
	muo.mutation.ClearExpiresAt()
	return muo
}

// SetUser sets the "user" edge to the User entity.
func (muo *MembershipUpdateOne) SetUser(u *User) *MembershipUpdateOne {
	return muo.SetUserID(u.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (muo *MembershipUpdateOne) SetGroup(g *Group) *MembershipUpdateOne {
	return muo.SetGroupID(g.ID)
}

// Mutation returns the MembershipMutation object of the builder.
func (muo *MembershipUpdateOne) Mutation() *MembershipMutation {
	return muo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (muo *MembershipUpdateOne) ClearUser() *MembershipUpdateOne {
	muo.mutation.ClearUser()
	return muo
}

// ClearGroup clears the "group" edge to the Group entity.
func (muo *MembershipUpdateOne) ClearGroup() *MembershipUpdateOne {
	muo.mutation.ClearGroup()
	return muo
}

// Where appends a list predicates to the MembershipUpdate builder.
func (muo *MembershipUpdateOne) Where(ps ...predicate.Membership) *MembershipUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MembershipUpdateOne) Select(field string, fields ...string) *MembershipUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Membership entity.
func (muo *MembershipUpdateOne) Save(ctx context.Context) (*Membership, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MembershipUpdateOne) SaveX(ctx context.Context) *Membership {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MembershipUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MembershipUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MembershipUpdateOne) check() error {
	if _, ok := muo.mutation.UserID(); muo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Membership.user"`)
	}
	if _, ok := muo.mutation.GroupID(); muo.mutation.GroupCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Membership.group"`)
	}
	return nil
}

func (muo *MembershipUpdateOne) sqlSave(ctx context.Context) (_node *Membership, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(membership.Table, membership.Columns, sqlgraph.NewFieldSpec(membership.FieldGroupID, field.TypeInt), sqlgraph.NewFieldSpec(membership.FieldUserID, field.TypeInt))
	if id, ok := muo.mutation.GroupID(); !ok {
		return nil, &ValidationError{Name: "group_id", err: errors.New(`ent: missing "Membership.group_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := muo.mutation.UserID(); !ok {
		return nil, &ValidationError{Name: "user_id", err: errors.New(`ent: missing "Membership.user_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !membership.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.IsPrimary(); ok {
		_spec.SetField(membership.FieldIsPrimary, field.TypeBool, value)
	}
	if muo.mutation.IsPrimaryCleared() {
		_spec.ClearField(membership.FieldIsPrimary, field.TypeBool)
	}
	if value, ok := muo.mutation.CreatedAt(); ok {
		_spec.SetField(membership.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := muo.mutation.ExpiresAt(); ok {
		_spec.SetField(membership.FieldExpiresAt, field.TypeTime, value)
	}
	if muo.mutation.ExpiresAtCleared() {
		_spec.ClearField(membership.FieldExpiresAt, field.TypeTime)
	}
	if muo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.UserTable,
			Columns: []string{membership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.UserTable,
			Columns: []string{membership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.GroupTable,
			Columns: []string{membership.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.GroupTable,
			Columns: []string{membership.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Membership{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{membership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
